version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: legal_anomaly_db
    environment:
      POSTGRES_DB: ${DB_NAME:-legal_anomaly_db}
      POSTGRES_USER: ${DB_USER:-myuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mypassword}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: 